# Default values for iqserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Big Bang Additions
domain: bigbang.dev
hostname: nexus-iq-server

istio:
  enabled: false
  iqserver:
    gateways:
    - "istio-system/public"

license_key: ""

admin:
  # Overriding the initial admin username/password is currently non-functional,
  # due to lack of API support for changing user passwords.  This field
  # currently only affects the credentials for the post-install job.
  username: admin
  password: admin123

certificates:
  image:
    repository: registry1.dso.mil/ironbank/sonatype/nexus-iq-server/nexus-iq-server
    tag: 1.107.0-01
    pullPolicy: IfNotPresent
  truststore:
    # If adding certificates to an existing truststore, the password should
    # match the password for the existing truststore.
    password: changeit
  customCAs:
    # DoD approved certificates from https://public.cyber.mil/unclass-dod_approved_external_pkis_trust_chains_v7/
    - secret: ca-certs-dod-trust-anchors
    - secret: ca-certs-dod-intermediate-dod-email-ca
    - secret: ca-certs-dod-intermediate-dod-id-ca
    - secret: ca-certs-dod-intermediate-dod-id-sw-ca
    - secret: ca-certs-dod-intermediate-dod-sw-ca
    - secret: ca-certs-eca-sha-1
    - secret: ca-certs-eca-sha-256
    - secret: ca-certs-ado-sha-256-cc-chain
    - secret: ca-certs-ado-sha-256-dt-chain
    - secret: ca-certs-boeing-sha-1
    - secret: ca-certs-carillon-federal-services
    - secret: ca-certs-department-of-state-trust-chain-1
    - secret: ca-certs-department-of-state-trust-chain-2
    - secret: ca-certs-entrust-nfi-trust-chain-1
    - secret: ca-certs-entrust-nfi-trust-chain-2
    - secret: ca-certs-entrust-ssp
    - secret: ca-certs-exostar-llc
    - secret: ca-certs-identrust-nfi
    - secret: ca-certs-lockheed-martin-sha-256
    - secret: ca-certs-nl-mod
    - secret: ca-certs-northrop-grumman-sha-256
    - secret: ca-certs-orc-nfi
    - secret: ca-certs-orc-ssp
    - secret: ca-certs-raytheon-sha-1
    - secret: ca-certs-raytheon-sha-256
    - secret: ca-certs-symantec-nfi-trust-chain-1
    - secret: ca-certs-symantec-nfi-trust-chain-2
    - secret: ca-certs-symantec-ssp-trust-chain-1
    - secret: ca-certs-symantec-ssp-trust-chain-2
    - secret: ca-certs-treasury-ssp-trust-chain-1
    - secret: ca-certs-treasury-ssp-trust-chain-2
    - secret: ca-certs-verizon-business-nfi
    - secret: ca-certs-verizon-business-ssp-trust-chain-1
    - secret: ca-certs-verizon-business-ssp-trust-chain-2

mail:
  enabled: false
  mailConfiguration: {}
  # mailConfiguration:
  #   hostname: mail.service.consul
  #   port: 25
  #   systemEmail: "root@ac2sp.army.mil"
  #   startTlsEnabled: true
sso:
  enabled: false
  idp_metadata: ''
  samlConfiguration: {}
  # samlConfiguration:
  #   identityProviderName: My SSO
  #   entityId: https://nexus-iq-server.example.com/api/v2/config/saml/metadata
  #   firstNameAttributeName: firstName
  #   lastNameAttributeName: lastName
  #   emailAttributeName: email
  #   usernameAttributeName: username
  #   groupsAttributeName: groups
  #   validateResponseSignature: true
  #   validateAssertionSignature: true


#namespaceOverride: nexus
replicaCount: 1
image:
  repository: registry1.dso.mil/ironbank/sonatype/nexus-iq-server/nexus-iq-server
  tag: 1.107.0-01
  pullPolicy: IfNotPresent

job_image:
  repository: registry1.dso.mil/ironbank/redhat/ubi/ubi8-minimal
  tag: 8.3
  pullPolicy: IfNotPresent

iq:
  name: nxiq
  hostname: iq-server.demo
  applicationPort: 8070
  adminPort: 8071
  memory: 1Gi
  # base 64 encoded license file with no line breaks
  licenseSecret: ""
  extraLabels:
  # enter appropriate proxy settings as required. NXIQ requires external access
  # to validate the license
  env:
    - name: JAVA_OPTS
      value: |-
        -Djava.util.prefs.userRoot=$${SONATYPE_WORK}/javaprefs
   #    -Dhttp.proxyHost=proxyserver
   #    -Dhttp.proxyPort=proxyport
   #    -Dhttps.proxyHost=proxyserver
   #    -Dhttps.proxyPort=proxyport
   #    -Dhttp.nonProxyHosts=nonproxyhosts

deploymentStrategy: Recreate
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "nexus-iq"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: "ClusterIP"
  port: 80

ingress:
  enabled: false
  annotations: {kubernetes.io/ingress.class: nginx}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostUI: iq-server.demo
  hostUIPath: /
  hostAdmin: admin.iq-server.demo
  hostAdminPath: /

  tls: []
    # - secretName: nexus-local-tls
    #   hosts:
    #     - iqserver.local
    #     - admin.iqserver.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  accessMode: ReadWriteOnce
  ## If defined, storageClass: <storageClass>
  ## If set to "-", storageClass: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClass spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  # storageClass: "-"
  storageSize: 1Gi
  # existingClaim:
  # annotations:
  #  "helm.sh/resource-policy": keep
  ## Configure the volume type.
  # volumeConfiguration:
  #   hostPath:
  #     path: /data/nxiq/

# configYaml is the full text of the config.yml file that will be passed to IQ Server
configYaml:
  # licenseFile: /etc/nexus-iq-license/sonatype-license.lic
  # baseUrl: http://iq-server.demo
  sonatypeWork: /sonatype-work
  server:
    applicationConnectors:
      - type: http
        port: 8070
    adminConnectors:
      - type: http
        port: 8071
    # HTTP request log settings.
    requestLog:
      appenders:
        #All appenders set to console
        - type: console
          # Do not display log statements below this threshold to stdout.
          threshold: INFO
          logFormat: "%clientHost %l %user [%date] \"%requestURL\" %statusCode %bytesSent %elapsedTime \"%header{User-Agent}\""

  createSampleData: true

  logging:

    # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
    level: ERROR

    # Logger-specific settings.
    loggers:
      "com.sonatype.insight.scan": INFO
      "eu.medsea.mimeutil.MimeUtil2": INFO
      "org.apache.http": INFO
      "org.apache.http.wire": ERROR
      "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
      "org.eclipse.jetty": INFO
      "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO   # WARNING: This reveals credentials at DEBUG level
      "com.sonatype.insight.audit":
        appenders:
          #All appenders set to console
          - type: console

            # Do not display log statements below this threshold to stdout.
            threshold: INFO

      "com.sonatype.insight.policy.violation":
        appenders:
          - type: console

            # Do not display log statements below this threshold to stdout.
            threshold: INFO

    appenders:

      # Settings for logging to stdout.
      - type: console

        # Do not display log statements below this threshold to stdout.
        threshold: INFO

        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
