# Default values for iqserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Big Bang Additions
domain: bigbang.dev
hostname: nexus-iq-server

istio:
  enabled: false
  iqserver:
    gateways:
    - "istio-system/public"

license_key: ""

admin:
  # Overriding the initial admin username/password is currently non-functional,
  # due to lack of API support for changing user passwords.  This field
  # currently only affects the credentials for the post-install job.
  username: admin
  password: admin123

certificates:
  # defaultMode of the custom-ca-certificates volume
  defaultMode: 420
  image:
    repository: registry1.dso.mil/ironbank/sonatype/nexus-iq-server/nexus-iq-server
    tag: 1.194.0-01
    pullPolicy: IfNotPresent
  truststore:
    # If adding certificates to an existing truststore, the password should
    # match the password for the existing truststore.
    password: changeit
  customCAs: []

mail:
  enabled: false
  mailConfiguration: {}
  # mailConfiguration:
  #   hostname: mail.service.consul
  #   port: 25
  #   systemEmail: "root@ac2sp.army.mil"
  #   startTlsEnabled: true
sso:
  enabled: false
  idp_metadata: ''
  samlConfiguration: {}
  # samlConfiguration:
  #   identityProviderName: My SSO
  #   entityId: https://nexus-iq-server.example.com/api/v2/config/saml/metadata
  #   firstNameAttributeName: firstName
  #   lastNameAttributeName: lastName
  #   emailAttributeName: email
  #   usernameAttributeName: username
  #   groupsAttributeName: groups
  #   validateResponseSignature: true
  #   validateAssertionSignature: true

statefulset:
  # This is not supported
  enabled: false
replicaCount: 1
image:
  repository: registry1.dso.mil/ironbank/sonatype/nexus-iq-server/nexus-iq-server
  tag: 1.194.0-01
  pullPolicy: IfNotPresent

job_image:
  repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9-minimal
  tag: 9.4
  pullPolicy: IfNotPresent

# Set fixOwner.enabled to true, when upgrading from IQ versions 1.117 or 1.100, to change file ownership.
fixOwner:
  enabled: false
  updateUser: 1000
  updateGroup: 1000

# Annotations to add to iq server pod
podAnnotations:

iq:
  name: nxiq
  hostname: iq-server.demo
  applicationPort: 8070
  adminPort: 8071
  memory: 1Gi
  # base 64 encoded license file with no line breaks
  licenseSecret: ""
  extraLabels:
  # enter appropriate proxy settings as required. NXIQ requires external access
  # to validate the license
  # add the following two lines to mount a secrets volume within the container at the specified location
  secretName: #secret-jks
  secretMountName: #/etc/secret-volume
  env:
    - name: JAVA_OPTS
      value: |-
        -Djava.util.prefs.userRoot=$${SONATYPE_WORK}/javaprefs
   #     # Leaving FIPS enabled results in issues with the keystore and establishing
   #     # a SSL connection with custom certificates
   #     -Dcom.redhat.fips=false
   #    -Dhttp.proxyHost=proxyserver
   #    -Dhttp.proxyPort=proxyport
   #    -Dhttps.proxyHost=proxyserver
   #    -Dhttps.proxyPort=proxyport
   #    -Dhttp.nonProxyHosts=nonproxyhosts
  # Configures the startup probe for IQ pod
  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 180
    timeoutSeconds: 2
    successThreshold: 1
  # Configures the liveness probe for IQ pod
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2
    successThreshold: 1
  # Configures the readiness probe for IQ pod
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
    timeoutSeconds: 2
    successThreshold: 1

# In conjunction with 'secretName' and 'secretMountName' above, this is an example of how to inject required password
# secrets into the runtime environment, and how to modify the startup of the server to utilize custom Java SSL stores.
#    - name: TRUSTSTORE_PASSWORD
#        valueFrom:
#          secretKeyRef:
#            name: secret-jks
#            key: truststorePassword
#    - name: KEYSTORE_PASSWORD
#      valueFrom:
#        secretKeyRef:
#          name: secret-jks
#          key: keystorePassword
#    - name: JAVA_OPTS
#      value: "-Djavax.net.ssl.keyStoreType=jks -Djavax.net.ssl.keyStore=/etc/secret-volume/keystore.jks -Djavax.net.ssl.keyStorePassword=$(KEYSTORE_PASSWORD) -Djavax.net.ssl.trustStoreType=jks -Djavax.net.ssl.trustStore=/etc/secret-volume/truststore.jks -Djavax.net.ssl.trustStorePassword=$(TRUSTSTORE_PASSWORD) -Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs"

deploymentStrategy: Recreate
imagePullSecrets:
  - name: private-registry

nameOverride: ""
fullnameOverride: "nexus-iq"
environment: "production"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true

service:
  type: "ClusterIP"
  port: 80

ingress:
  enabled: false
  annotations: {kubernetes.io/ingress.class: nginx}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostUI: iq-server.demo
  hostUIPath: /
  hostAdmin: admin.iq-server.demo
  hostAdminPath: /

  tls: []
    # - secretName: nexus-local-tls
    #   hosts:
    #     - iqserver.local
    #     - admin.iqserver.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  ## If defined, storageClass: <storageClass>
  ## If set to "-", storageClass: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClass spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  # storageClass: "-"
  storageSize: 1Gi
  # existingClaim:
  # existingLogClaim:
  # annotations:
  #  "helm.sh/resource-policy": keep
  ## Configure the volume type.
  # storageClass: "-"
  # volumeConfiguration:
  #   hostPath:
  #     path: /data/nxiq/
  # If you want to use existing PersistentDisk with data, you can create a PV for it by uncommenting the following lines. (Currently supports GCE PD only)
  # pdName: nexus-data-disk
  # fsType: ext4
  # Uncomment below 2 lines, if you want to use an existing GCE PersistentDisk for IQ Logs.
  # logpdName: nexus-log-disk
  # logfsType: ext4

# configYaml is the full text of the config.yml file that will be passed to IQ Server
configYaml:
  # baseUrl: http://iq-server.demo
  sonatypeWork: /sonatype-work
  # licenseFile: /etc/nexus-iq-license/sonatype-license.lic
  server:
    applicationConnectors:
      - type: http
        port: 8070
    adminConnectors:
      - type: http
        port: 8071
    # HTTP request log settings.
    requestLog:
      appenders:
        #All appenders set to console
        - type: file
          currentLogFilename: /var/log/nexus-iq-server/request.log
          # Do not display log statements below this threshold to stdout.
          # threshold: INFO
          logFormat: "%clientHost %l %user [%date] \"%requestURL\" %statusCode %bytesSent %elapsedTime \"%header{User-Agent}\""
          archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
          archivedFileCount: 50

  createSampleData: true

  logging:

    # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
    level: ERROR

    # Logger-specific settings.
    loggers:
      "com.sonatype.insight.scan": INFO
      "eu.medsea.mimeutil.MimeUtil2": INFO
      "org.apache.http": INFO
      "org.apache.http.wire": ERROR
      "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
      "org.eclipse.jetty": INFO
      "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO   # WARNING: This reveals credentials at DEBUG level
      "com.sonatype.insight.audit":
        appenders:
          #All appenders set to console
          - type: console

            # Do not display log statements below this threshold to stdout.
            threshold: INFO

      "com.sonatype.insight.policy.violation":
        appenders:
          - type: console

            # Do not display log statements below this threshold to stdout.
            threshold: INFO

    appenders:
      # Settings for logging to stdout.
      - type: console
        # Do not display log statements below this threshold to stdout.
        threshold: INFO
        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
      - type: file
        # Do not display log statements below this threshold to stdout.
        threshold: ALL
        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
        # The file to which current statements will be logged.
        currentLogFilename: /var/log/nexus-iq-server/clm-server.log
        archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
        archivedFileCount: 50
