apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "iqserver.fullname" . }}
  labels:
    tags.datadoghq.com/env: {{ .Values.environment }} # Unified service tag - Deployment Env tag
    tags.datadoghq.com/service: {{ .Release.Namespace }} # Unified service tag - Deployment Service tag
    tags.datadoghq.com/version: {{ .Values.image.tag }} # Unified service tag - Deployment Version tag
    {{- include "iqserver.labels" . | nindent 4 }}
    {{- if .Values.iq.extraLabels }}
      {{- with .Values.iq.extraLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  selector:
    matchLabels:
      {{- include "iqserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iqserver.selectorLabels" . | nindent 8 }}
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/config.mode: "socket"
        tags.datadoghq.com/env: {{ .Values.environment }} # Unified service tag - Deployment Env tag
        tags.datadoghq.com/service: {{ .Release.Namespace }} # Unified service tag - Deployment Service tag
        tags.datadoghq.com/version: {{ .Values.image.tag }} # Unified service tag - Deployment Version tag
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.10.1"
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "iqserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or (.Values.certificates.customCAs) (.Values.fixOwner.enabled) }}
      initContainers:
      {{- end }}
      {{- if .Values.certificates.customCAs }}
        - name: {{ .Chart.Name }}-truststore-gen
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.certificates.image.repository }}:{{ .Values.certificates.image.tag }}"
          imagePullPolicy: {{ quote .Values.certificates.image.pullPolicy }}
          env: {{ toYaml .Values.iq.env | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          command:
            - sh
            - -c
            - |
                CA_DIR=/opt/customcas
                TRUSTSTORE_SOURCE=/etc/pki/java/cacerts
                TRUSTSTORE_PATH=/opt/trust/cacerts
                if [ -f "$TRUSTSTORE_SOURCE" ]; then
                  cp -f "$TRUSTSTORE_SOURCE" "$TRUSTSTORE_PATH"
                  chmod 0644 "$TRUSTSTORE_PATH"
                fi
                for ca in $(ls "$CA_DIR"); do
                  keytool -import -noprompt -file "$CA_DIR/$ca" -alias "$ca" -J-Dcom.redhat.fips=false \
                          -keystore "$TRUSTSTORE_PATH" \
                          -storepass {{ quote .Values.certificates.truststore.password }}
                done
          volumeMounts:
            - name: ephemeral-truststore
              mountPath: /opt/trust
              readOnly: false
            - name: custom-ca-certificates
              mountPath: /opt/customcas
              readOnly: true
      {{- end }}
      {{- if .Values.fixOwner.enabled }}
        - name: chown-vols
          image: "busybox:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
          command: ['sh', '-c', 'chown -R {{ .Values.fixOwner.updateUser }}:{{ .Values.fixOwner.updateGroup }} /var/log/nexus-iq-server {{ .Values.configYaml.sonatypeWork }}']
          volumeMounts:
            - mountPath: {{ .Values.configYaml.sonatypeWork }}
              name: nxiq-pv-data
            - mountPath: /var/log/nexus-iq-server
              name: nxiq-pv-log
            - mountPath: /etc/nexus-iq-server
              name: config-volume
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SONATYPE_WORK
              value: {{ .Values.configYaml.sonatypeWork }}
            - name: DD_LOGS_INJECTION
              value: "true"
            {{- toYaml .Values.iq.env | nindent 12 }}
          ports:
            - name: application
              containerPort: {{ .Values.iq.applicationPort }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.iq.adminPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /ping
              port: admin
              {{- if .Values.iq.startupProbe }}
                {{- toYaml .Values.iq.startupProbe | nindent 12 }}
              {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              port: admin
              {{- if .Values.iq.livenessProbe }}
                {{- toYaml .Values.iq.livenessProbe | nindent 12 }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: application
              {{- if .Values.iq.readinessProbe }}
                {{- toYaml .Values.iq.readinessProbe | nindent 12 }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.configYaml.sonatypeWork }}
              name: nxiq-pv-data
            - mountPath: /var/log/nexus-iq-server
              name: nxiq-pv-log
            - mountPath: /etc/nexus-iq-server
              name: config-volume
            {{- if .Values.license_key }}
            - mountPath: /etc/nexus-iq-license
              name: license-volume
            {{- end }}
            {{- if .Values.certificates.customCAs }}
            - name: ephemeral-truststore
              mountPath: /etc/pki/java
              readOnly: false
            {{- end }}
      volumes:
        - name: nxiq-pv-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (include "iqserver.fullname" .) "data") }}
        - name: nxiq-pv-log
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingLogClaim | default (printf "%s-%s" (include "iqserver.fullname" .) "log") }}
        - name: config-volume
          configMap:
            name: {{ template "iqserver.fullname" . }}-conf
            items:
              - key: config.yml
                path: config.yml
        {{- if .Values.license_key }}
        - name: license-volume
          secret:
            secretName: {{ template "iqserver.fullname" . }}-license
        {{- end }}
        {{- if .Values.certificates.customCAs }}
        - name: ephemeral-truststore
          emptyDir:
            medium: Memory
        - name: custom-ca-certificates
          projected:
            defaultMode: {{ .Values.certificates.defaultMode | default "420" }}
            sources:
              {{- range $customCA := .Values.certificates.customCAs }}
              - secret:
                  name: {{ $customCA.secret }}
              {{- end }}
        {{- end }}
        {{- if and (.Values.iq.secretName) (.Values.iq.secretMountName) }}
        - name: secret-volume
          secret:
            secretName: {{ .Values.iq.secretName }}
        {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
