{{- if or .Values.sso.enabled .Values.mail.enabled  }}
# temporarily removed (and) operator and .Values.license_key from above line
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  name: post-install
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 60
      {{- if .Values.sso.enabled }}
      volumes:
        - name: idp
          configMap:
            name: {{ template "iqserver.fullname" . }}-sso
            items:
            - key: idpmetadata.xml
              path: idpmetadata.xml
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.job_image.repository }}:{{ .Values.job_image.tag }}"
        imagePullPolicy: {{ .Values.job_image.pullPolicy }}
        name: post-install
        {{- if .Values.sso.enabled }}
        volumeMounts:
          - mountPath: /tmp/
            name: idp
        {{- end }}
        command:
          - sh
        args:
          - -c
          - |-
            BASE_URL="http://{{ template "iqserver.fullname" . }}.{{ template "iqserver.fullname" . }}-server.svc.cluster.local:{{ .Values.iq.applicationPort }}";
            until curl --head localhost:15000; do echo "Waiting for Sidecar"; sleep 30; done; echo "Sidecar available";
            {{- if .Values.sso.enabled }}
            while [ "$(curl -s "${BASE_URL}/rest/product/license")" == "No valid product license installed." ]; do echo "Waiting for License"; sleep 5; done;
            curl -X PUT \
                -u {{ quote .Values.admin.username }}:{{ quote .Values.admin.password }} \
                "${BASE_URL}/api/v2/config/saml" \
                -F identityProviderXml=@/tmp/idpmetadata.xml \
                -F samlConfiguration='{{ .Values.sso.samlConfiguration | toJson }}';
            {{- end }}
            {{- if .Values.mail.enabled }}
            curl -X PUT \
                -u {{ quote .Values.admin.username }}:{{ quote .Values.admin.password }} \
                -H "Content-Type: application/json" \
                -v "${BASE_URL}/api/v2/config/mail" \
                -d '{{ .Values.mail.mailConfiguration | toJson}}';
            {{- end }}
            curl -fsI -X POST http://localhost:15020/quitquitquit;
            exit
        resources: {}
      restartPolicy: Never
status: {}
{{- end }}
